application: sinmetal-slide
module: default
version: 201407181817
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 100ms
  max_concurrent_requests: 50

handlers:
- url: /favicon.ico
  static_files: present/static/favicon.ico
  upload: present/static/favicon.ico
- url: /static
  static_dir: present/static
- url: /images
  static_dir: images
- url: /.*
  script: _go_app

nobuild_files: ^(201[0-9]/)